# Generated by Django 2.2 on 2019-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
