# Generated by Django 2.2 on 2019-04-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_answer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
